---
- name: Destroy Infrastructure with Terraform
  terraform:
    project_path: "{{ playbook_dir }}/roles/tf-infrastructure/terraform"
    force_init: true
    state: absent
    variables:
      hcloud_token: "{{ hetzner_token }}"
      datacenter: "{{ datacenter }}"
      master_servertype: "{{ master_servertype }}"
      worker_servertype: "{{ worker_servertype }}"
      worker_count: "{{ worker_count }}"
      floatip_count: "{{ floatip_count }}"
      use_my_ip: "{{ use_my_ip }}"
      my_ip_tag: "{{ my_ip_tag }}"
      domain: "{{ domain }}"
  register: tf
